### ISSUE TITLE
Script listet nicht alle Bücher

### ISSUE THREAD

**Issue by he3ndor** [rtfmkiesel/edubase-downloader#1]
Hallo,
vielen Dank für das Bereitstellen des PY. Es hat alles wunderbar funktioniert. Nun habe ich ein Buch mit der Nummer "18493", das das PY nicht anzeigen oder finden kann.

![grafik](https://github.com/user-attachments/assets/47e735b2-c09b-4086-8712-89eed618e7a5)
![grafik](https://github.com/user-attachments/assets/edbb33c7-4c57-4c03-9d34-a5876a3a7475)

**Comment by rtfmkiesel** [comment]
Ohne das du mir deinen Account gibst, kann ich nicht überprüfen warum dir das Buch nicht angezeigt wird. Wenn du etwas Javascript verstehst, kannst du das [Query](https://github.com/rtfmkiesel/edubase-downloader/blob/2c340628ff0e0139c6a5a2dd3a8f3090450497f1/edubasedl.py#L26) für die IDs untersuchen und anpassen.

Für einen einfachen "Fix" kannst du die Zeilen 111-112 löschen. (Nicht mit Notepad öffnen) Danach kannst du die ID trotzdem eingeben. Evtl. klappt das bereits.

**Comment by he3ndor** [comment]
Thx. hat geklappt mit dem Code 111-112.
