### ISSUE TITLE
only downloads default books

### ISSUE THREAD

**Issue by blossomgang** [rtfmkiesel/edubase-downloader#2]
i have an activated license. the books arent recognized in the cli.

**Comment by rtfmkiesel** [comment]
You know what, there are other book types now. Can you send me the HTML of "https://app.edubase.ch/#library" ? Please note, if you attach it to this issue, everyone knows what books you have. If you do not want that, send it via a Xwitter DM.

**Comment by blossomgang** [comment]
your twitter dms are for premium users only. ill just drop it here: https://www.file-upload.net/download-15386014/EdubaseReader.html.html if thats the wrong one please lmk i dont exactly know how this works

**Comment by rtfmkiesel** [comment]
Ah, apparently Twitter changed that setting for me. Anyway, this is the correct HTML, thanks. I'm gonna update the script later with a better "book detection method".

**Comment by rtfmkiesel** [comment]
I updated (quite a bit) of the code. 

@blossomgang Can you try again? Delete your local copy of the repo and start from a fresh `git clone`, as I switched a core component.

**Comment by blossomgang** [comment]
works perfectly fine now!

youre the best, thanks!
